version: '3.1'

services:
        progra_segura:
                environment:
                        llave: ${llave}
                        bdName: ${bdName}
                        bdUser: ${bdUser}
                        bdPassword: ${bdPassword}
                        bdHost: ${bdHost}
                        bdPort: 3306
                build: ./finalSegura6
                restart: always
                volumes:
                        - ./finalSegura6:/code
                ports:
                        -  8080:8080
        bd:
                image: mariadb
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: ${bdPassword}
                        MYSQL_DATABASE: miBD
                volumes:
                        - ./data:/var/lib/mysql
        nginx:
                image: nginx
                restart: always
                volumes:
                        - ./nginx:/etc/nginx/conf.d
                depends_on:
                        - progra_segura
                ports:
                        - 9000:80